# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'WhatFlower' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhatFlower
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'ProgressHUD'
end
