# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def climator_pod
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'
    pod 'Alamofire', '~> 5.0.0-rc.2'
end

target 'Climator' do
  platform :ios, '12.4'
  use_frameworks!
  climator_pod
end
