
def flash_chat_pod
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Analytics'
    pod 'SVProgressHUD'
    pod 'ChameleonFramework'
end

target 'Flash Chat' do
  platform :ios, '12.0'
  use_frameworks!
  flash_chat_pod
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
    end
  end
end
